library(readr)
library(dplyr)
covid_coocs_hansard_20 <- read.csv("covid_cooccurrence_20.csv")
covid_coocs_release_20 <- read.csv("covid_coocs_release_20.csv")
covid_coocs_speech_20 <- read.csv("covid_coocs_speech_20.csv")
covid_coocs_legi_20 <- read.csv("covid_coocs_legiDoc_20.csv")
covid_coocs_cord_20 <- read_csv("cord_cooccurrence_20.csv")
covid_coocs_hansard_20$type <- "Hansard"
covid_coocs_release_20$type <- "Release"
covid_coocs_speech_20$type <- "Speech"
covid_coocs_legi_20$type <- "LegiDoc"
covid_coocs_cord_20$type <- "Research"
covid_coocs_cord_20 <-covid_coocs_cord_20 %>%
  rename(X=X1)
combined_coocs <- rbind(covid_coocs_hansard_20,covid_coocs_release_20,covid_coocs_legi_20,covid_coocs_speech_20,covid_coocs_cord_20)
combined_coocs.agg <- aggregate(type~from+to,combined_coocs,paste,collapse="&")
colnames(combined_coocs.agg) <- c("source","target","class")
allNodes.1 <- unique(covid_coocs_hansard_20[,c(2,5)])
colnames(allNodes.1) <- c("Id","type")
allNodes.2 <- unique(covid_coocs_hansard_20[,c(3,5)])
colnames(allNodes.2) <- c("Id","type")
allNodes.3 <- unique(covid_coocs_release_20[,c(2,5)])
colnames(allNodes.3) <- c("Id","type")
allNodes.4 <- unique(covid_coocs_release_20[,c(3,5)])
colnames(allNodes.4) <- c("Id","type")
allNodes.5 <- unique(covid_coocs_speech_20[,c(2,5)])
colnames(allNodes.5) <- c("Id","type")
allNodes.6 <- unique(covid_coocs_speech_20[,c(3,5)])
colnames(allNodes.6) <- c("Id","type")
allNodes.7 <- unique(covid_coocs_legi_20[,c(2,5)])
colnames(allNodes.7) <- c("Id","type")
allNodes.8 <- unique(covid_coocs_legi_20[,c(3,5)])
colnames(allNodes.8) <- c("Id","type")
allNodes.9 <- unique(covid_coocs_cord_20[,c(2,5)])
colnames(allNodes.9) <- c("Id","type")
allNodes.10 <- unique(covid_coocs_cord_20[,c(3,5)])
colnames(allNodes.10) <- c("Id","type")
allNodes <- unique(rbind(allNodes.1,allNodes.2,allNodes.3,allNodes.4,allNodes.5,allNodes.6,allNodes.7,allNodes.8,allNodes.9,allNodes.10))
allNodes.agg <- aggregate(type~Id,allNodes,paste,collapse="&")
write_csv(combined_coocs.agg,"net.csv")
write_csv(allNodes.agg,"net_nodes.csv")
